"""init

Revision ID: 71ef19e95677
Revises: 0491c41b927b
Create Date: 2019-07-16 08:24:26.360768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ef19e95677'
down_revision = '0491c41b927b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
