"""init

Revision ID: 3b6c30915292
Revises: 71ef19e95677
Create Date: 2019-07-16 23:41:16.508274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6c30915292'
down_revision = '71ef19e95677'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
